import { Currency } from "../types/types";

export const currencies: Currency[] = [
  {
    code: "CDF",
    name: "Congo Kinshasa Franc",
    prefix: null,
    suffix: "CDF",
  },
  {
    code: "LBP",
    name: "Lebanon Pound",
    prefix: "£",
    suffix: null,
  },
  {
    code: "SGD",
    name: "Singapore Dollars",
    prefix: "$",
    suffix: null,
  },
  {
    code: "UYU",
    name: "Uruguay Peso",
    prefix: "$U",
    suffix: null,
  },
  {
    code: "MYR",
    name: "Malaysian Ringgit",
    prefix: "RM",
    suffix: null,
  },
  {
    code: "USD",
    name: "US Dollars",
    prefix: "$",
    suffix: null,
  },
  {
    code: "PHP",
    name: "Philippine Pesos",
    prefix: "₱",
    suffix: null,
  },
  {
    code: "KPW",
    name: "Korea (North) Won",
    prefix: "₩",
    suffix: null,
  },
  {
    code: "MNT",
    name: "Mongolia Tughrik",
    prefix: "₮",
    suffix: null,
  },
  {
    code: "HRK",
    name: "Croatian Kuna",
    prefix: null,
    suffix: " kn.",
  },
  {
    code: "HUF",
    name: "Hungarian Forints",
    prefix: null,
    suffix: " Ft.",
  },
  {
    code: "KHR",
    name: "Cambodia Riel",
    prefix: "៛",
    suffix: null,
  },
  {
    code: "CAD",
    name: "Canadian Dollars",
    prefix: "$",
    suffix: null,
  },
  {
    code: "PAB",
    name: "Panamanian Balboa",
    prefix: "$",
    suffix: null,
  },
  {
    code: "ILS",
    name: "Israel Sheqel",
    prefix: "₪",
    suffix: null,
  },
  {
    code: "JPY",
    name: "Japanese Yen",
    prefix: "¥",
    suffix: null,
  },
  {
    code: "QAR",
    name: "Qatar Riyal",
    prefix: null,
    suffix: "﷼",
  },
  {
    code: "OMR",
    name: "Oman Rial",
    prefix: null,
    suffix: "﷼",
  },
  {
    code: "BIF",
    name: "Burundi Franc",
    prefix: null,
    suffix: "BIF",
  },
  {
    code: "TJS",
    name: "Tajikistan Somoni",
    prefix: null,
    suffix: "TJS",
  },
  {
    code: "ALL",
    name: "Albania Lek",
    prefix: "L",
    suffix: null,
  },
  {
    code: "HTG",
    name: "Haiti Gourde",
    prefix: null,
    suffix: "HTG",
  },
  {
    code: "MXN",
    name: "Mexican Pesos",
    prefix: "$",
    suffix: null,
  },
  {
    code: "FJD",
    name: "Fiji Dollar",
    prefix: "$",
    suffix: null,
  },
  {
    code: "SCR",
    name: "Seychelles Rupee",
    prefix: "₨",
    suffix: null,
  },
  {
    code: "ZMW",
    name: "Zambia Kwacha",
    prefix: "ZK",
    suffix: null,
  },
  {
    code: "GIP",
    name: "Gibraltar Pound",
    prefix: "£",
    suffix: null,
  },
  {
    code: "SHP",
    name: "Saint Helena Pound",
    prefix: "£",
    suffix: null,
  },
  {
    code: "KZT",
    name: "Kazakhstan Tenge",
    prefix: "₸",
    suffix: null,
  },
  {
    code: "AUD",
    name: "Australian Dollars",
    prefix: "$",
    suffix: null,
  },
  {
    code: "BDT",
    name: "Bangladesh Taka",
    prefix: null,
    suffix: "BDT",
  },
  {
    code: "RWF",
    name: "Rwanda Franc",
    prefix: null,
    suffix: "RWF",
  },
  {
    code: "AMD",
    name: "Armenia Dram",
    prefix: null,
    suffix: "դր.",
  },
  {
    code: "GHS",
    name: "Ghana Cedi",
    prefix: null,
    suffix: "GHS",
  },
  {
    code: "GEL",
    name: "Georgia Lari",
    prefix: null,
    suffix: "GEL",
  },
  {
    code: "INR",
    name: "Indian Rupees",
    prefix: "Rs",
    suffix: null,
  },
  {
    code: "AFN",
    name: "Afghanistan Afghani",
    prefix: null,
    suffix: "؋",
  },
  {
    code: "LKR",
    name: "Sri Lanka Rupee",
    prefix: "₨",
    suffix: null,
  },
  {
    code: "CUC",
    name: "Cuba Convertible Peso",
    prefix: null,
    suffix: "CUC",
  },
  {
    code: "CHF",
    name: "Swiss Francs",
    prefix: null,
    suffix: " fr.",
  },
  {
    code: "CRC",
    name: "Columbian Pesos",
    prefix: "₡",
    suffix: null,
  },
  {
    code: "SAR",
    name: "Saudi Riyal",
    prefix: "﷼",
    suffix: null,
  },
  {
    code: "TTD",
    name: "Trinidad and Tobago Dollar",
    prefix: "TT$",
    suffix: null,
  },
  {
    code: "XCD",
    name: "East Caribbean Dollar",
    prefix: "$",
    suffix: null,
  },
  {
    code: "CZK",
    name: "Czech Koruny",
    prefix: "kč",
    suffix: null,
  },
  {
    code: "ETB",
    name: "Ethiopia Birr",
    prefix: null,
    suffix: "ETB",
  },
  {
    code: "CLP",
    name: "Chiliean Peso",
    prefix: "$",
    suffix: null,
  },
  {
    code: "STD",
    name: "Dobra",
    prefix: null,
    suffix: "STD",
  },
  {
    code: "KES",
    name: "Kenya Shilling",
    prefix: "KSh",
    suffix: null,
  },
  {
    code: "IRR",
    name: "Iran Rial",
    prefix: null,
    suffix: "﷼",
  },
  {
    code: "DJF",
    name: "Djibouti Franc",
    prefix: null,
    suffix: "DJF",
  },
  {
    code: "VND",
    name: "Viet Nam Dong",
    prefix: null,
    suffix: "₫",
  },
  {
    code: "CUP",
    name: "Cuba Peso",
    prefix: "$MN",
    suffix: null,
  },
  {
    code: "WST",
    name: "Samoa Tala",
    prefix: null,
    suffix: "WST",
  },
  {
    code: "EGP",
    name: "Egypt Pound",
    prefix: "£",
    suffix: null,
  },
  {
    code: "MAD",
    name: "Morocco Dirham",
    prefix: null,
    suffix: ".د.م",
  },
  {
    code: "LSL",
    name: "Lesotho Loti",
    prefix: null,
    suffix: "LSL",
  },
  {
    code: "MVR",
    name: "Maldives (Maldive Islands)",
    prefix: null,
    suffix: "MVR",
  },
  {
    code: "AZN",
    name: "Azerbaijan New Manat",
    prefix: "₼",
    suffix: null,
  },
  {
    code: "SOS",
    name: "Somalia Shilling",
    prefix: "S",
    suffix: null,
  },
  {
    code: "NZD",
    name: "New Zealand Dollars",
    prefix: "$",
    suffix: null,
  },
  {
    code: "JMD",
    name: "Jamaica Dollar",
    prefix: "J$",
    suffix: null,
  },
  {
    code: "NGN",
    name: "Nigerian Naira",
    prefix: "₦",
    suffix: null,
  },
  {
    code: "UZS",
    name: "Uzbekistan Som",
    prefix: "so’m",
    suffix: null,
  },
  {
    code: "EUR",
    name: "Euros",
    prefix: "€",
    suffix: null,
  },
  {
    code: "VUV",
    name: "Vanuatu Vatu",
    prefix: null,
    suffix: "VUV",
  },
  {
    code: "UAH",
    name: "Ukrainian Hryvna",
    prefix: "₴",
    suffix: null,
  },
  {
    code: "UGX",
    name: "Uganda Shilling",
    prefix: "USh",
    suffix: null,
  },
  {
    code: "MRO",
    name: "Mauritania Ouguiya",
    prefix: null,
    suffix: "MRO",
  },
  {
    code: "ZAR",
    name: "South African Rand",
    prefix: "R",
    suffix: null,
  },
  {
    code: "SYP",
    name: "Syria Pound",
    prefix: "£",
    suffix: null,
  },
  {
    code: "BZD",
    name: "Belize Dollar",
    prefix: "BZ$",
    suffix: null,
  },
  {
    code: "BRL",
    name: "Brazil Reais",
    prefix: "R$",
    suffix: null,
  },
  {
    code: "SEK",
    name: "Swedish Kronar",
    prefix: null,
    suffix: " kr.",
  },
  {
    code: "VEF",
    name: "Venezulean Bolivar",
    prefix: "Bs",
    suffix: null,
  },
  {
    code: "TZS",
    name: "Tanzania Shilling",
    prefix: "TSh",
    suffix: null,
  },
  {
    code: "BOB",
    name: "Bolivia Boliviano",
    prefix: "Bs.",
    suffix: null,
  },
  {
    code: "BHD",
    name: "Bahrain Dinar",
    prefix: null,
    suffix: ".د.ب",
  },
  {
    code: "PLN",
    name: "Polish Zloty",
    prefix: null,
    suffix: " zł.",
  },
  {
    code: "DOP",
    name: "Dominican Peso",
    prefix: "RD$",
    suffix: null,
  },
  {
    code: "KYD",
    name: "Cayman Islands Dollar",
    prefix: "$",
    suffix: null,
  },
  {
    code: "KRW",
    name: "South Korean Won",
    prefix: "₩",
    suffix: null,
  },
  {
    code: "RON",
    name: "Romanian New Lei",
    prefix: "L",
    suffix: null,
  },
  {
    code: "AED",
    name: "UAE Dirham",
    prefix: "AED",
    suffix: null,
  },
  {
    code: "BTN",
    name: "Bhutan Ngultrum",
    prefix: null,
    suffix: "BTN",
  },
  {
    code: "KGS",
    name: "Kyrgyzstan Som",
    prefix: "сом",
    suffix: null,
  },
  {
    code: "ISK",
    name: "Icelandic Krona",
    prefix: null,
    suffix: " kr.",
  },
  {
    code: "SDG",
    name: "Sudan Pound",
    prefix: null,
    suffix: "SDG",
  },
  {
    code: "THB",
    name: "Thai Baht",
    prefix: "฿",
    suffix: null,
  },
  {
    code: "GBP",
    name: "British Pounds",
    prefix: "£",
    suffix: null,
  },
  {
    code: "SVC",
    name: "El Salvador Colon",
    prefix: "$",
    suffix: null,
  },
  {
    code: "BND",
    name: "Brunei Darussalam Dollar",
    prefix: "$",
    suffix: null,
  },
  {
    code: "MWK",
    name: "Malawi Kwacha",
    prefix: "MK",
    suffix: null,
  },
  {
    code: "YER",
    name: "Yemen Rial",
    prefix: null,
    suffix: "﷼",
  },
  {
    code: "BYN",
    name: "Belarus Ruble",
    prefix: null,
    suffix: "p.",
  },
  {
    code: "ZWD",
    name: "Zimbabwe Dollar",
    prefix: "Z$",
    suffix: null,
  },
  {
    code: "COP",
    name: "Columbian Pesos",
    prefix: "$",
    suffix: null,
  },
  {
    code: "IDR",
    name: "Indonesia Rupiah",
    prefix: "Rp",
    suffix: null,
  },
  {
    code: "FKP",
    name: "Falkland Islands (Malvina)",
    prefix: "£",
    suffix: null,
  },
  {
    code: "NIO",
    name: "Nicaragua Cordoba",
    prefix: "C$",
    suffix: null,
  },
  {
    code: "DKK",
    name: "Danish Kroner",
    prefix: null,
    suffix: " kr.",
  },
  {
    code: "PGK",
    name: "Papua New Guinea Kina",
    prefix: null,
    suffix: "PGK",
  },
  {
    code: "HNL",
    name: "Honduras Lempira",
    prefix: "L",
    suffix: null,
  },
  {
    code: "TRY",
    name: "Turkish New Lira",
    prefix: "₺",
    suffix: null,
  },
  {
    code: "LYD",
    name: "Libya Dinar",
    prefix: null,
    suffix: ".د.ل",
  },
  {
    code: "LAK",
    name: "Laos Kip",
    prefix: "₭",
    suffix: null,
  },
  {
    code: "MGA",
    name: "Madagascar Ariary",
    prefix: null,
    suffix: "MGA",
  },
  {
    code: "SZL",
    name: "Swaziland Lilangeni",
    prefix: null,
    suffix: "SZL",
  },
  {
    code: "BGN",
    name: "Bulgaria Lev",
    prefix: "лв",
    suffix: null,
  },
  {
    code: "IQD",
    name: "Iraq Dinar",
    prefix: null,
    suffix: ".د.ع",
  },
  {
    code: "TWD",
    name: "Taiwan Dollars",
    prefix: "$",
    suffix: null,
  },
  {
    code: "CVE",
    name: "Cape Verde Escudo",
    prefix: null,
    suffix: "CVE",
  },
  {
    code: "TND",
    name: "Tunisia Dinar",
    prefix: null,
    suffix: ".د.ت",
  },
  {
    code: "SRD",
    name: "Suriname Dollar",
    prefix: "$",
    suffix: null,
  },
  {
    code: "XAF",
    name: "CFA Franc BEAC",
    prefix: null,
    suffix: "XAF",
  },
  {
    code: "JOD",
    name: "Jordan Dinar",
    prefix: null,
    suffix: ".د.إ",
  },
  {
    code: "GMD",
    name: "Gambia Dalasi",
    prefix: null,
    suffix: "GMD",
  },
  {
    code: "PYG",
    name: "Paraguay Guarani",
    prefix: null,
    suffix: "Gs",
  },
  {
    code: "TOP",
    name: "Tonga Pa'anga",
    prefix: null,
    suffix: "TOP",
  },
  {
    code: "LTL",
    name: "Lithuania Litas",
    prefix: "Lt",
    suffix: null,
  },
  {
    code: "BWP",
    name: "Botswana Pula",
    prefix: "P",
    suffix: null,
  },
  {
    code: "KMF",
    name: "Comoros Franc",
    prefix: null,
    suffix: "KMF",
  },
  {
    code: "TMT",
    name: "Turkmenistan Manat",
    prefix: null,
    suffix: "TMT",
  },
  {
    code: "HKD",
    name: "Hong Kong Dollars",
    prefix: "HK$",
    suffix: null,
  },
  {
    code: "LVL",
    name: "Latvia Lat",
    prefix: null,
    suffix: "Ls",
  },
  {
    code: "MDL",
    name: "Moldova Leu",
    prefix: null,
    suffix: "MDL",
  },
  {
    code: "KWD",
    name: "Kuwait Dinar",
    prefix: null,
    suffix: ".د.ك",
  },
  {
    code: "BBD",
    name: "Barbados Dollar",
    prefix: "$",
    suffix: null,
  },
  {
    code: "LRD",
    name: "Liberia Dollar",
    prefix: "$",
    suffix: null,
  },
  {
    code: "MOP",
    name: "Macau Pataca",
    prefix: null,
    suffix: "MOP",
  },
  {
    code: "GNF",
    name: "Guinea Franc",
    prefix: null,
    suffix: "GNF",
  },
  {
    code: "BYR",
    name: "Belarus Ruble (2000-2016)",
    prefix: null,
    suffix: "p.",
  },
  {
    code: "PKR",
    name: "Pakistan Rupee",
    prefix: "₨",
    suffix: null,
  },
  {
    code: "XPF",
    name: "CFP Franc",
    prefix: null,
    suffix: "XPF",
  },
  {
    code: "PEN",
    name: "Peruvian Nuevo Sol",
    prefix: "S/.",
    suffix: null,
  },
  {
    code: "RSD",
    name: "Serbian Dinar",
    prefix: null,
    suffix: "din",
  },
  {
    code: "MKD",
    name: "Macedonian Denar",
    prefix: null,
    suffix: " ден.",
  },
  {
    code: "CNY",
    name: "Chinese Yuan",
    prefix: "¥",
    suffix: null,
  },
  {
    code: "GYD",
    name: "Guyana Dollar",
    prefix: "$",
    suffix: null,
  },
  {
    code: "MZN",
    name: "Mozambique Metical",
    prefix: "MT",
    suffix: null,
  },
  {
    code: "DZD",
    name: "Algeria Dinar",
    prefix: null,
    suffix: ".د.ج",
  },
  {
    code: "ARS",
    name: "Argentinean Peso",
    prefix: "$",
    suffix: null,
  },
  {
    code: "SLL",
    name: "Sierra Leone Leone",
    prefix: null,
    suffix: "SLL",
  },
  {
    code: "NOK",
    name: "Norwegian Kroner",
    prefix: null,
    suffix: " kr.",
  },
  {
    code: "BSD",
    name: "Bahamas Dollar",
    prefix: "$",
    suffix: null,
  },
  {
    code: "MMK",
    name: "Myanmar (Burma) Kyat",
    prefix: "K",
    suffix: null,
  },
  {
    code: "BAM",
    name: "Bosnia and Herzegovina Co",
    prefix: "KM",
    suffix: null,
  },
  {
    code: "SBD",
    name: "Solomon Islands Dollar",
    prefix: "$",
    suffix: null,
  },
  {
    code: "NAD",
    name: "Namibia Dollar",
    prefix: "$",
    suffix: null,
  },
  {
    code: "ANG",
    name: "Netherlands Antilles Guil",
    prefix: "ƒ",
    suffix: null,
  },
  {
    code: "MUR",
    name: "Mauritius Rupee",
    prefix: "₨",
    suffix: null,
  },
  {
    code: "BMD",
    name: "Bermuda Dollar",
    prefix: "$",
    suffix: null,
  },
  {
    code: "NPR",
    name: "Nepal Rupee",
    prefix: "₨",
    suffix: null,
  },
  {
    code: "AOA",
    name: "Angola Kwanza",
    prefix: null,
    suffix: "AOA",
  },
  {
    code: "AWG",
    name: "Aruba Guilder",
    prefix: "ƒ",
    suffix: null,
  },
  {
    code: "GTQ",
    name: "Guatemala Quetzal",
    prefix: "Q",
    suffix: null,
  },
  {
    code: "RUB",
    name: "Russian Rouble",
    prefix: null,
    suffix: "₽",
  },
];

export const currencyMap: Record<string, string | null> = currencies.reduce(
  (map, currency) => {
    map[currency.code] = currency.prefix;
    return map;
  },
  {} as Record<string, string | null>
);
